server:
  port: 8081

spring:
  application:
    name: Inventory Connected
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: halinamarket
    password: 'halinamarket'
